apiVersion: v1
kind: ConfigMap
metadata:
  name: cartorio-mod8-script
  namespace: cartorio-mod8
data:
  bootstrap-pipeline.sh: |-
    #!/usr/bin/env bash
    set -euo pipefail

    REGION="${AWS_REGION:-us-east-1}"
    ENVIRONMENT="${ENVIRONMENT:-dev}"
    ARTIFACT_BUCKET="${ARTIFACT_BUCKET:-cartorio-${ENVIRONMENT}-cicd-artifacts}"
    PIPELINE_NAME="cartorio-${ENVIRONMENT}-pipeline"
    GITHUB_OWNER="${GITHUB_OWNER:?Defina GITHUB_OWNER}"
    GITHUB_REPO="${GITHUB_REPO:?Defina GITHUB_REPO}"
    GITHUB_BRANCH="${GITHUB_BRANCH:-main}"
    GITHUB_TOKEN="${GITHUB_TOKEN:?Defina GITHUB_TOKEN}"

    if [[ "${REGION}" == "us-east-1" ]]; then
      aws s3api create-bucket --bucket "${ARTIFACT_BUCKET}" --region "${REGION}" || true
    else
      aws s3api create-bucket --bucket "${ARTIFACT_BUCKET}" --region "${REGION}" \
        --create-bucket-configuration "LocationConstraint=${REGION}" || true
    fi

    ROLE_ARN="$(aws iam create-role --role-name "cartorio-${ENVIRONMENT}-codepipeline" \
      --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["codepipeline.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}' \
      --query Role.Arn --output text 2>/dev/null || aws iam get-role --role-name "cartorio-${ENVIRONMENT}-codepipeline" --query Role.Arn --output text)"

    aws iam attach-role-policy --role-name "cartorio-${ENVIRONMENT}-codepipeline" \
      --policy-arn arn:aws:iam::aws:policy/AWSCodePipelineFullAccess || true
    aws iam attach-role-policy --role-name "cartorio-${ENVIRONMENT}-codepipeline" \
      --policy-arn arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess || true
    aws iam attach-role-policy --role-name "cartorio-${ENVIRONMENT}-codepipeline" \
      --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess || true

    BUILD_ROLE="$(aws iam create-role --role-name "cartorio-${ENVIRONMENT}-codebuild" \
      --assume-role-policy-document '{"Version":"2012-10-17","Statement":[{"Effect":"Allow","Principal":{"Service":["codebuild.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}' \
      --query Role.Arn --output text 2>/dev/null || aws iam get-role --role-name "cartorio-${ENVIRONMENT}-codebuild" --query Role.Arn --output text)"

    aws iam attach-role-policy --role-name "cartorio-${ENVIRONMENT}-codebuild" \
      --policy-arn arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess || true
    aws iam attach-role-policy --role-name "cartorio-${ENVIRONMENT}-codebuild" \
      --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess || true

    aws codebuild create-project \
      --name "cartorio-${ENVIRONMENT}-build" \
      --source type=GITHUB,location="https://github.com/${GITHUB_OWNER}/${GITHUB_REPO}.git" \
      --artifacts type=CODEPIPELINE \
      --environment type=LINUX_CONTAINER,image=aws/codebuild/standard:7.0,computeType=BUILD_GENERAL1_SMALL \
      --service-role "${BUILD_ROLE}" 2>/dev/null || true

    aws codepipeline create-pipeline --cli-input-json "{
      \"pipeline\": {
        \"name\": \"${PIPELINE_NAME}\",
        \"roleArn\": \"${ROLE_ARN}\",
        \"artifactStore\": {\"type\": \"S3\", \"location\": \"${ARTIFACT_BUCKET}\"},
        \"stages\": [
          {\"name\": \"Source\", \"actions\": [
            {\"name\": \"GitHubSource\",\"actionTypeId\": {\"category\": \"Source\",\"owner\": \"ThirdParty\",\"provider\": \"GitHub\",\"version\": \"1\"},
             \"outputArtifacts\": [{\"name\": \"SourceOutput\"}],
             \"configuration\": {\"Owner\": \"${GITHUB_OWNER}\",\"Repo\": \"${GITHUB_REPO}\",\"Branch\": \"${GITHUB_BRANCH}\",\"OAuthToken\": \"${GITHUB_TOKEN}\"}}
          ]},
          {\"name\": \"Build\", \"actions\": [
            {\"name\": \"CodeBuild\",\"actionTypeId\": {\"category\": \"Build\",\"owner\": \"AWS\",\"provider\": \"CodeBuild\",\"version\": \"1\"},
             \"inputArtifacts\": [{\"name\": \"SourceOutput\"}],
             \"outputArtifacts\": [{\"name\": \"BuildOutput\"}],
             \"configuration\": {\"ProjectName\": \"cartorio-${ENVIRONMENT}-build\"}}
          ]}
        ]
      }
    }" 2>/dev/null || true
