apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - configmap-settings.yaml
  - configmap-script.yaml
  - job-aggregate-outputs.yaml
  - deployment-backend.yaml
  - service-backend.yaml
  - deployment-frontend.yaml
  - service-frontend.yaml
