apiVersion: v1
kind: ConfigMap
metadata:
  name: cartorio-mod6-script
  namespace: cartorio-mod6
data:
  create-kms.sh: |-
    #!/usr/bin/env bash
    set -euo pipefail

    REGION="${AWS_REGION:-us-east-1}"
    ENVIRONMENT="${ENVIRONMENT:-dev}"

    KEY_ID="$(aws kms create-key \
      --region "${REGION}" \
      --description "Cartorio Digital (${ENVIRONMENT}) citizen credentials" \
      --key-usage SIGN_VERIFY \
      --origin AWS_KMS \
      --query KeyMetadata.KeyId --output text)"

    aws kms create-alias \
      --region "${REGION}" \
      --alias-name "alias/cartorio/${ENVIRONMENT}/citizen" \
      --target-key-id "${KEY_ID}" || true

    KEY_ARN="$(aws kms describe-key --region "${REGION}" --key-id "${KEY_ID}" --query KeyMetadata.Arn --output text)"

    aws ssm put-parameter \
      --region "${REGION}" \
      --name "/cartorio/${ENVIRONMENT}/kms/citizen_key_arn" \
      --type String \
      --value "${KEY_ARN}" \
      --overwrite
