#!/bin/bash
#
# Script de setup do apêndice EJBCA-CE
# Este script documenta a estrutura de arquivos criados para o Capítulo 11 (Apêndice)
#

set -e

echo "=================================="
echo "Apêndice EJBCA-CE - Estrutura"
echo "=================================="
echo ""
echo "Estrutura de arquivos criados:"
echo ""
echo "apendices/ejbca-ce/"
echo "├── README.md               - Visão geral do EJBCA-CE e índice de capítulos"
echo "├── 01_introducao.md        - Introdução ao EJBCA-CE, histórico e licenciamento"
echo "├── 02_arquitetura.md       - Arquitetura e componentes (CA, RA, VA)"
echo "├── 03_instalacao.md        - Guia de instalação com Docker e Docker Compose"
echo "├── 04_gestao_certificados.md - Emissão, renovação, revogação e auditoria"
echo "├── 05_protocolos.md        - ACME, SCEP, EST, CMP e REST API"
echo "├── 06_comparacao.md        - Comparação com AWS Private CA e outras soluções"
echo "├── 07_casos_uso.md         - Casos de uso práticos no Cartório Digital"
echo "└── setup.sh                - Este script (documentação da estrutura)"
echo ""
echo "=================================="
echo "Conteúdo dos capítulos"
echo "=================================="
echo ""
echo "Capítulo 1 - Introdução:"
echo "  • O que é o EJBCA-CE"
echo "  • Histórico e evolução"
echo "  • Licenciamento LGPL"
echo "  • Por que usar no Cartório Digital"
echo ""
echo "Capítulo 2 - Arquitetura:"
echo "  • Componentes (CA, RA, VA)"
echo "  • Perfis de certificado"
echo "  • Protocolos de inscrição"
echo "  • Camadas de persistência e segurança"
echo ""
echo "Capítulo 3 - Instalação:"
echo "  • Instalação com Docker (método rápido)"
echo "  • Docker Compose com PostgreSQL"
echo "  • Configuração inicial"
echo "  • Criação da primeira CA"
echo ""
echo "Capítulo 4 - Gestão de Certificados:"
echo "  • Ciclo de vida de certificados"
echo "  • Métodos de emissão (Web UI, CLI, REST API, ACME)"
echo "  • Renovação e revogação"
echo "  • Auditoria e relatórios"
echo ""
echo "Capítulo 5 - Protocolos:"
echo "  • Servidor ACME (compatível com Certbot)"
echo "  • REST API completa"
echo "  • SCEP para dispositivos de rede"
echo "  • EST para IoT"
echo "  • CMP para ambientes empresariais"
echo ""
echo "Capítulo 6 - Comparação:"
echo "  • EJBCA-CE vs AWS Private CA"
echo "  • Análise de custos"
echo "  • Casos de uso ideais para cada solução"
echo "  • Arquitetura híbrida"
echo ""
echo "Capítulo 7 - Casos de Uso:"
echo "  • PKI para assinatura de documentos oficiais"
echo "  • mTLS para microsserviços internos"
echo "  • Certificados para totens de autoatendimento"
echo "  • Timestamping (RFC 3161)"
echo ""
echo "=================================="
echo "Integração com o projeto principal"
echo "=================================="
echo ""
echo "O README.md principal foi atualizado com:"
echo "  • Nova seção 'Apêndices' no sumário"
echo "  • Link direto para apendices/ejbca-ce/README.md"
echo "  • Descrição do conteúdo do apêndice"
echo ""
echo "=================================="
echo "Próximos passos sugeridos"
echo "=================================="
echo ""
echo "1. Ler o README.md do apêndice para visão geral"
echo "2. Seguir o Capítulo 3 (instalação) para subir EJBCA-CE localmente"
echo "3. Experimentar os casos de uso do Capítulo 7"
echo "4. Comparar com implementações AWS Private CA do Módulo 2"
echo ""
echo "✅ Apêndice EJBCA-CE criado com sucesso!"

