name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Backend Build
        run: ./scripts/ci/backend_build.sh
      - name: Frontend Build
        run: ./scripts/ci/frontend_build.sh
      - name: Security Scans
        run: ./scripts/ci/security_scans.sh
      - name: Upload Evidence
        run: ./scripts/ci/upload_evidence.sh
