apiVersion: batch/v1
kind: Job
metadata:
  name: cartorio-mod3-enable-mtls
  namespace: cartorio-mod3
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: cartorio-aws-cli
      containers:
        - name: aws-cli
          image: amazon/aws-cli:2.13.11
          command: ["/bin/sh", "-c", "chmod +x /scripts/enable-mtls.sh && /scripts/enable-mtls.sh"]
          env:
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: cartorio-mod3-settings
                  key: awsRegion
                  optional: true
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: cartorio-mod3-settings
                  key: environment
                  optional: true
            - name: DOMAIN_NAME
              valueFrom:
                configMapKeyRef:
                  name: cartorio-mod3-settings
                  key: domainName
                  optional: true
            - name: TRUST_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: cartorio-mod3-settings
                  key: trustBucket
                  optional: true
            - name: CERT_ARN
              valueFrom:
                configMapKeyRef:
                  name: cartorio-mod3-settings
                  key: certArn
                  optional: true
          volumeMounts:
            - name: scripts
              mountPath: /scripts
      volumes:
        - name: scripts
          configMap:
            name: cartorio-mod3-script
            defaultMode: 0755
  backoffLimit: 1
